services:
  airflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather-airflow
    command: standalone
    environment:
      AIRFLOW_HOME: /opt/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CORE__DEFAULT_TIMEZONE: Europe/Moscow
      TZ: Europe/Moscow
    ports:
      - "8080:8080"
    volumes:
      - airflow-data:/opt/airflow
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ../..:/opt/project
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - "0"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

volumes:
  airflow-data: